[server]
name = "roxy"
logfile = "logs/access.log"
loglevel = "debug"
max_connections = 1024

listen = ["127.0.0.1:8100", "192.168.1.2:8100"]

[[match]]
uri = "/"
serve = "/static"


[[match]]
uri = "/api"
algorithm = "WRR"
forward = [
    { address = "127.0.0.1:8080", weight = 1 },
    { address = "127.0.0.1:8081", weight = 3 },
    { address = "127.0.0.1:8082", weight = 2 },
]
